    <option value="Aventura">Aventura</option>
    <option value="Bal Harbour">Bal Harbour</option>
    <option value="Bay Harbor Islands">Bay Harbor Islands</option>
    <option value="Biscayne Park">Biscayne Park</option>
    <option value="Carol City">Carol City</option>
    <option value="Coral Gables">Coral Gables</option>
    <option value="Cutler Bay">Cutler Bay</option>
    <option value="Cutler Ridge">Cutler Ridge</option>
    <option value="Doral">Doral</option>
    <option value="El Portal">El Portal</option>
    <option value="Fisher Island">Fisher Island</option>
    <option value="Florida City">Florida City</option>
    <option value="Golden Beach">Golden Beach</option>
    <option value="Florida City">Florida City</option>
    <option value="Golden Beach">Golden Beach</option>
    <option value="Hialeah">Hialeah</option>
    <option value="Hialeah Gardens">Hialeah Gardens</option>
    <option value="Homestead">Homestead</option>
    <option value="Indian Creek">Indian Creek</option>
    <option value="Islandia">Islandia</option>
    <option value="Kendall">Kendall</option>
    <option value="Key Biscayne">Key Biscayne</option>
    <option value="Medley">Medley</option>
    <option value="Miami">Miami</option>
    <option value="Miami Beach">Miami Beach</option>
    <option value="Miami Gardens">Miami Gardens</option>
    <option value="Miami Lakes">Miami Lakes</option>
    <option value="Miami Shores">Miami Shores</option>
    <option value="Miami Springs">Miami Springs</option>
    <option value="Naranja">Naranja</option>
    <option value="North Bay Village">North Bay Village</option>
    <option value="North Miami">North Miami</option>
    <option value="North Miami Beach">North Miami Beach</option>
    <option value="Ojus">Ojus</option>
    <option value="Opa-Locka">Opa-Locka</option>
    <option value="Palmetto Bay">Palmetto Bay</option>
    <option value="Perrine">Perrine</option>
    <option value="Pinecrest">Pinecrest</option>
    <option value="South Miami">South Miami</option>
    <option value="Sunny Isles">Sunny Isles</option>
    <option value="Surfside">Surfside</option>
    <option value="Sweetwater">Sweetwater</option>
    <option value="Universal Park">Universal Park</option>
    <option value="Virginia Gardens">Virginia Gardens</option>
    <option value="West Miami">West Miami</option>